api_gateway:
   url: http://apigateway.daeipresal40399.eur.ad.sag/rest/apigateway
   user: Administrator
   password: "manage"
---

aliases:
  MicroServiceAlias:
    type: simple
    value: http://localhost:5555